 version: 2.1
jobs:
  build:
    docker:
      - image: dannydainton/htmlextra
    steps:
      - run: |
          docker run -t -v $(pwd):/etc/newman dannydainton/htmlextra run collection.json -r cli,htmlextra
      - store_artifacts:
          path: ~/test-results/newman
