version: 2.1
jobs:
  build:
    docker: 
      - image: dannydainton/htmlextra
    steps:
      - checkout
      - newman/newman-run:
          collection: https://www.getpostman.com/collections/83fe94d56b18938765bd
          timeout: "300000"
          additional-options: -r cli,htmlextra
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/newman
            cp ./newman/*.html ~/test-results/newman/
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/newman
