version: 2.1
jobs:
  build:
    docker:
      - image: dannydainton/htmlextra
    steps:
      - checkout
      - run:
         command: |
           mkdir -p ~/test-results/newman
           newman run ./tests/Restful_Booker_Collection.postman_collection.json -e ./tests/Restful_Booker_Environment.postman_environment.json -r cli,htmlextra
           cp ./newman/*.html ~/test-results/newman/
      - store_artifacts:
          path: ~/test-results/newman
