version: 2.1
jobs:
  build:
    docker:
      - image: dannydainton/htmlextra
    steps:
      - checkout
      - run: newman run https://www.getpostman.com/collections/83fe94d56b18938765bd -r cli,htmlextra
      - store_artifacts:
          path: ~/test-results/newman
