version: 2.1
jobs:
  build:
    docker:
      - image: dannydainton/htmlextra
    working_directory: /tmp
    steps:
      - checkout
      - run: newman run https://www.getpostman.com/collections/83fe94d56b18938765bd -r cli,htmlextra
      - store_artifacts:
          path: /tmp/newman

      - store_artifacts:
          path: /newman
