version: 2
jobs:
  run_tests:
    docker: 
     - image: dannydainton/htmlextra
    steps:
      - checkout
      - run: run tests/Restful_Booker_Collection.postman_collection.json -e ./tests/Restful_Booker_Environment.postman_environment.json -r cli,htmlextra
      - store_artifacts:
          path: ~/newman
workflows:
    version: 2
    main:
        jobs:
            - run_tests
