version: 2.1
jobs:
  build:
    docker:
      - image: dannydainton/htmlextra
    steps:
      - checkout
      - run:
         command: |
           mkdir -p ~/test-results/newman
           newman run https://www.getpostman.com/collections/83fe94d56b18938765bd -r cli,htmlextra
           cp ./newman/*.html ~/test-results/newman/
      - store_artifacts:
          path: ~/test-results/newman
